<?php
$lang = [
    // Common
    'messages' => 'My Messages',
    'send_message' => 'Send New Message',
    'feedback' => 'Feedback',
    'give_feedback' => 'Give Feedback',
    'appointments' => 'My Appointments',
    'new_appointment' => 'New Appointment',
    'subject' => 'Subject',
    'from' => 'From',
    'to' => 'To',
    'date' => 'Date',
    'status' => 'Status',
    'request' => 'Request',
    'view' => 'View',
    'location' => 'Location',
    'organizer' => 'Organizer',
    'attendee' => 'Attendee',
    'start' => 'Start',
    'end' => 'End',
    'rating' => 'Rating',
    'comments' => 'Comments',
    'submitted_date' => 'Submitted Date',
    'feedback_given' => 'Feedback I\'ve Given',
    'feedback_received' => 'Feedback on My Requests',
    'message' => 'Message',
    'send' => 'Send',
    'select_recipient' => 'Select recipient',
    'select_request' => 'Select request',
    'recipient' => 'Recipient',
    'body' => 'Message Body',
    'related_request' => 'Related Request',
    'choose_resolved_request' => 'Choose resolved request',
    'submit_feedback' => 'Submit Feedback',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'dashboard' => 'Dashboard',
    'language' => 'Language'
];
?>
